
REDIS_HASH_NAME = 'IDIRECT_CONTOUR_TESTRUN_HASH'
REDIS_DATASET_KEY = 'TESTRUN_DATASET'
REDIS_UPDATED_KEY = 'TESTRUN_UPDATED_TIME'
REDIS_MODIFIED_KEY = 'TESTRUN_MODIFIED_TIME'
REDIS_TIME_FORMAT= '%a, %b %d %Y %H:%M:%S %z'
